### ISSUE TITLE
nuxt: "permission_denied" when trying load data via router

### ISSUE THREAD

**Issue by MarvinMiles** [flamelink/examples#2]
Hi! Thank you for your work!

Nuxt example works fine until router had used. I mean when the page rendered first time everything works ok, but when you come to product page via nuxt-link in navbar you will recieve an error:

> permission_denied at /flamelink/media/files/1534891433497: Client doesn't have permission to access the desired data.

Demo:
https://boring-bhaskara-75ba20.netlify.com/products/

My "asyncData":

```
async asyncData({ app }) {
      const products = await app.flamelink.content.get('products', { populate: ['image'] })
      return { products }
}
```

How can I fix this? Thanks

**Comment by jperasmus** [comment]
Hi 👋 

This means that your Firebase realtime DB rules aren't allowing `.read` access from the browser. You'll have to update the rules to allow access. When the SDK runs server-side it bypasses any of these rules.

https://firebase.google.com/docs/database/security/

**Comment by MarvinMiles** [comment]
It helps. Thank you again!)
